import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() => runApp(const ArcadeX());
const bg = Color(0xFF090B12), panel = Color(0xFF151A27), purple = Color(0xFF9B7BFF), cyan = Color(0xFF45D9FF), green = Color(0xFF65E572);

class ArcadeX extends StatelessWidget {
  const ArcadeX({super.key});
  @override Widget build(BuildContext context) => MaterialApp(title: 'ArcadeX', debugShowCheckedModeBanner: false,
    theme: ThemeData.dark(useMaterial3: true).copyWith(scaffoldBackgroundColor: bg, colorScheme: ColorScheme.fromSeed(seedColor: purple, brightness: Brightness.dark)),
    home: const HomePage());
}

class HomePage extends StatefulWidget { const HomePage({super.key}); @override State<HomePage> createState() => _HomePageState(); }
class _HomePageState extends State<HomePage> {
  Map<String,int> best = {};
  @override void initState(){super.initState(); _load();}
  Future<void> _load() async { final p=await SharedPreferences.getInstance(); if(!mounted)return; setState(()=>best={'snake':p.getInt('best_snake')??0,'flappy':p.getInt('best_flappy')??0,'memory':p.getInt('best_memory')??0,'ttt':p.getInt('score_ttt')??0}); }
  Future<void> _open(Widget page) async { await Navigator.push(context,MaterialPageRoute(builder:(_)=>page)); _load(); }
  @override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(20,24,20,24),children:[
    const Text('ARCADEX',style:TextStyle(fontSize:32,fontWeight:FontWeight.w900,letterSpacing:5)), const SizedBox(height:6),
    Text('YOUR OFFLINE POCKET ARCADE',style:TextStyle(color:Colors.white.withValues(alpha:.55),letterSpacing:1.7,fontSize:11,fontWeight:FontWeight.bold)),const SizedBox(height:24),
    Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF29204E),Color(0xFF151B31)]),borderRadius:BorderRadius.circular(24),border:Border.all(color:purple.withValues(alpha:.4))),child:const Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('ARCADE MODE',style:TextStyle(color:cyan,fontWeight:FontWeight.w900,letterSpacing:2)),SizedBox(height:8),Text('4 games. Zero internet.',style:TextStyle(fontSize:19,fontWeight:FontWeight.w800)),SizedBox(height:4),Text('Play anywhere, anytime.',style:TextStyle(color:Colors.white70))])),Icon(Icons.sports_esports_rounded,size:54,color:purple)])),
    const SizedBox(height:26),const Text('CHOOSE YOUR GAME',style:TextStyle(letterSpacing:2,fontWeight:FontWeight.w900)),const SizedBox(height:14),
    _GameTile(emoji:'🐍',title:'SNAKE X',subtitle:'Swipe anywhere • Beat your best',color:green,best:best['snake']??0,onTap:()=>_open(const SnakeGame())),
    _GameTile(emoji:'🐦',title:'FLAPPY',subtitle:'Fly through the green pipes',color:cyan,best:best['flappy']??0,onTap:()=>_open(const FlappyGame())),
    _GameTile(emoji:'🧠',title:'MEMORY MATCH',subtitle:'Find every matching pair',color:const Color(0xFFFFC857),best:best['memory']??0,onTap:()=>_open(const MemoryGame())),
    _GameTile(emoji:'❌⭕',title:'TIC-TAC-TOE',subtitle:'Choose Noob, Mid or Pro',color:purple,best:best['ttt']??0,onTap:()=>_open(const DifficultyPage())),
    const SizedBox(height:10),Center(child:Text('100% OFFLINE • ARCADEX',style:TextStyle(color:Colors.white.withValues(alpha:.3),letterSpacing:1.5,fontSize:10))),
  ])));
}
class _GameTile extends StatelessWidget {
  final String emoji,title,subtitle; final Color color; final int best; final VoidCallback onTap;
  const _GameTile({required this.emoji,required this.title,required this.subtitle,required this.color,required this.best,required this.onTap});
  @override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.only(bottom:12),child:Material(color:panel,borderRadius:BorderRadius.circular(20),child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(20),child:Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(borderRadius:BorderRadius.circular(20),border:Border.all(color:color.withValues(alpha:.25))),child:Row(children:[Container(width:58,height:58,alignment:Alignment.center,decoration:BoxDecoration(color:color.withValues(alpha:.12),borderRadius:BorderRadius.circular(16)),child:Text(emoji,style:const TextStyle(fontSize:27))),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:TextStyle(fontWeight:FontWeight.w900,letterSpacing:1.2,color:color)),const SizedBox(height:5),Text(subtitle,style:const TextStyle(color:Colors.white70,fontSize:12))])),Column(children:[const Icon(Icons.emoji_events_rounded,color:Color(0xFFFFC857),size:18),Text('$best',style:const TextStyle(fontWeight:FontWeight.w900))]),const SizedBox(width:6),const Icon(Icons.chevron_right,color:Colors.white54)])))));
}
class ScoreBox extends StatelessWidget { final String label,value; final Color color; const ScoreBox({super.key,required this.label,required this.value,required this.color}); @override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.symmetric(horizontal:18,vertical:10),decoration:BoxDecoration(color:panel,borderRadius:BorderRadius.circular(14)),child:Column(children:[Text(label,style:TextStyle(color:color,fontSize:10,fontWeight:FontWeight.w900,letterSpacing:1.4)),Text(value,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900))])); }

// SNAKE X — swipe gestures cover the entire game board.
class SnakeGame extends StatefulWidget { const SnakeGame({super.key}); @override State<SnakeGame> createState()=>_SnakeGameState(); }
class _SnakeGameState extends State<SnakeGame> {
  final rng=Random(); List<Point<int>> snake=[]; Point<int> food=const Point(8,8),dir=const Point(1,0),nextDir=const Point(1,0); Timer? timer; int score=0,best=0; bool over=false,started=false; static const n=20;
  @override void initState(){super.initState();_loadBest();_reset();}
  Future<void> _loadBest()async{final p=await SharedPreferences.getInstance();if(mounted)setState(()=>best=p.getInt('best_snake')??0);}
  void _reset(){timer?.cancel();snake=[const Point(9,10),const Point(8,10),const Point(7,10)];dir=const Point(1,0);nextDir=dir;score=0;over=false;started=false;_placeFood();if(mounted)setState((){});}
  void _placeFood(){do{food=Point(rng.nextInt(n),rng.nextInt(n));}while(snake.contains(food));}
  void _start(){if(over){_reset();}if(started)return;setState(()=>started=true);timer=Timer.periodic(Duration(milliseconds:max(75,155-score*2)),(_)=>_tick());}
  void _turn(Point<int>d){if(d.x+dir.x==0&&d.y+dir.y==0)return;nextDir=d;_start();}
  void _swipe(DragEndDetails d){final v=d.velocity.pixelsPerSecond;if(v.distance<70)return;if(v.dx.abs()>v.dy.abs()){_turn(Point(v.dx>0?1:-1,0));}else{_turn(Point(0,v.dy>0?1:-1));}}
  void _tick(){if(!mounted||over)return;setState((){dir=nextDir;final h=Point(snake.first.x+dir.x,snake.first.y+dir.y);if(h.x<0||h.y<0||h.x>=n||h.y>=n||snake.contains(h)){over=true;timer?.cancel();return;}snake.insert(0,h);if(h==food){score++;_placeFood();}else{snake.removeLast();}});if(over)_saveBest();}
  Future<void> _saveBest()async{final p=await SharedPreferences.getInstance();if(score>best){best=score;await p.setInt('best_snake',best);if(mounted)setState((){});}}
  @override void dispose(){timer?.cancel();super.dispose();}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('🐍 SNAKE X'),actions:[IconButton(onPressed:_reset,icon:const Icon(Icons.refresh))]),body:SafeArea(child:Column(children:[Padding(padding:const EdgeInsets.symmetric(horizontal:24,vertical:8),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[ScoreBox(label:'SCORE',value:'$score',color:green),ScoreBox(label:'BEST',value:'$best',color:cyan)])),Expanded(child:Center(child:LayoutBuilder(builder:(context,c){final side=min(c.maxWidth-24,c.maxHeight-12);return GestureDetector(behavior:HitTestBehavior.opaque,onPanEnd:_swipe,onTap:_start,child:SizedBox(width:side,height:side,child:CustomPaint(painter:SnakePainter(snake:snake,food:food,n:n))));}))),Padding(padding:const EdgeInsets.fromLTRB(12,8,12,18),child:Text(over?'GAME OVER • TAP TO RESTART':started?'SWIPE ANYWHERE ON THE BOARD':'TAP OR SWIPE TO START',style:TextStyle(color:over?Colors.redAccent:Colors.white60,fontWeight:FontWeight.w900,letterSpacing:1.2)))])));
}
class SnakePainter extends CustomPainter { final List<Point<int>>snake;final Point<int>food;final int n;SnakePainter({required this.snake,required this.food,required this.n});@override void paint(Canvas c,Size s){final cell=s.width/n;c.drawRRect(RRect.fromRectAndRadius(Offset.zero&s,const Radius.circular(18)),Paint()..color=const Color(0xFF0D1420));final grid=Paint()..color=Colors.white.withValues(alpha:.045)..style=PaintingStyle.stroke..strokeWidth=.5;for(int i=0;i<=n;i++){c.drawLine(Offset(i*cell,0),Offset(i*cell,s.height),grid);c.drawLine(Offset(0,i*cell),Offset(s.width,i*cell),grid);}c.drawCircle(Offset((food.x+.5)*cell,(food.y+.5)*cell),cell*.34,Paint()..color=const Color(0xFFFF647C)..maskFilter=const MaskFilter.blur(BlurStyle.normal,4));for(int i=snake.length-1;i>=0;i--){final p=snake[i];final r=Rect.fromLTWH(p.x*cell+1,p.y*cell+1,cell-2,cell-2);final color=i==0?const Color(0xFFB6FF76):Color.lerp(const Color(0xFF45D879),const Color(0xFF157F72),i/snake.length)!;c.drawRRect(RRect.fromRectAndRadius(r,Radius.circular(cell*.28)),Paint()..color=color);if(i==0){final eye=Paint()..color=const Color(0xFF10221B);c.drawCircle(Offset(r.left+cell*.32,r.top+cell*.34),cell*.07,eye);c.drawCircle(Offset(r.left+cell*.66,r.top+cell*.34),cell*.07,eye);}}}@override bool shouldRepaint(covariant SnakePainter old)=>true;}

// FLAPPY — tap to flap, with classic-style green pipes.
class FlappyGame extends StatefulWidget{const FlappyGame({super.key});@override State<FlappyGame> createState()=>_FlappyGameState();}
class _FlappyGameState extends State<FlappyGame>{double birdY=0,velocity=0,pipeX=1.25,gapY=0;int score=0,best=0;bool started=false,over=false;Timer? timer;final rng=Random();
 @override void initState(){super.initState();_load();}Future<void>_load()async{final p=await SharedPreferences.getInstance();if(mounted)setState(()=>best=p.getInt('best_flappy')??0);}
 void _startOrFlap(){if(over){_reset();return;}if(!started){setState(()=>started=true);timer=Timer.periodic(const Duration(milliseconds:24),(_)=>_tick());}setState(()=>velocity=-5.2);}
 void _reset(){timer?.cancel();setState((){birdY=0;velocity=0;pipeX=1.25;gapY=(rng.nextDouble()-.5)*.55;score=0;started=false;over=false;});}
 void _tick(){if(!mounted||over)return;setState((){velocity+=.22;birdY+=velocity*.012;pipeX-=.012;if(pipeX<-.15){pipeX=1.2;gapY=(rng.nextDouble()-.5)*.75;score++;}if(birdY<-.53||birdY>.53||((pipeX-.30).abs()<.09&&(birdY<gapY-.22||birdY>gapY+.22))){over=true;timer?.cancel();}});if(over)_save();}
 Future<void>_save()async{final p=await SharedPreferences.getInstance();if(score>best){best=score;await p.setInt('best_flappy',best);if(mounted)setState((){});}}
 @override void dispose(){timer?.cancel();super.dispose();}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('🐦 FLAPPY')),body:SafeArea(child:Column(children:[Padding(padding:const EdgeInsets.all(16),child:Row(mainAxisAlignment:MainAxisAlignment.spaceAround,children:[ScoreBox(label:'SCORE',value:'$score',color:cyan),ScoreBox(label:'BEST',value:'$best',color:green)])),Expanded(child:Padding(padding:const EdgeInsets.fromLTRB(14,0,14,18),child:GestureDetector(onTap:_startOrFlap,child:ClipRRect(borderRadius:BorderRadius.circular(22),child:CustomPaint(painter:FlappyPainter(birdY:birdY,pipeX:pipeX,gapY:gapY),child:const SizedBox.expand()))))),Padding(padding:const EdgeInsets.only(bottom:16),child:Text(over?'CRASHED • TAP TO RETRY':started?'TAP TO FLAP':'TAP TO START',style:const TextStyle(fontWeight:FontWeight.w900,letterSpacing:1.5,color:Colors.white70)))])));
}
class FlappyPainter extends CustomPainter{final double birdY,pipeX,gapY;FlappyPainter({required this.birdY,required this.pipeX,required this.gapY});@override void paint(Canvas c,Size s){c.drawRect(Offset.zero&s,Paint()..shader=const LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[Color(0xFF4ABCEB),Color(0xFFB8F0FF)]).createShader(Offset.zero&s));final cloud=Paint()..color=Colors.white.withValues(alpha:.78);for(final p in [Offset(s.width*.18,s.height*.18),Offset(s.width*.72,s.height*.28),Offset(s.width*.48,s.height*.09)]){c.drawCircle(p,15,cloud);c.drawCircle(p+const Offset(15,4),12,cloud);}final x=s.width*pipeX,gap=s.height*.25,center=s.height*(.5+gapY),top=center-gap/2,bottom=center+gap/2;final pipe=Paint()..shader=const LinearGradient(colors:[Color(0xFF14853C),Color(0xFF65E572),Color(0xFF159447)]).createShader(Rect.fromLTWH(x-22,0,44,s.height));c.drawRect(Rect.fromLTRB(x-15,0,x+15,top),pipe);c.drawRect(Rect.fromLTRB(x-15,bottom,x+15,s.height*.91),pipe);c.drawRect(Rect.fromLTRB(x-22,top-13,x+22,top),pipe);c.drawRect(Rect.fromLTRB(x-22,bottom,x+22,bottom+13),pipe);c.drawRect(Rect.fromLTWH(0,s.height*.91,s.width,s.height*.09),Paint()..color=const Color(0xFF9B6B3B));c.drawRect(Rect.fromLTWH(0,s.height*.91,s.width,5),Paint()..color=const Color(0xFF62C94E));final b=Offset(s.width*.30,s.height*(.5+birdY));c.save();c.translate(b.dx,b.dy);c.rotate(birdY*.5);c.drawOval(const Rect.fromLTWH(-15,-11,30,23),Paint()..color=const Color(0xFFFFD84A));c.drawOval(const Rect.fromLTWH(-10,-5,16,12),Paint()..color=const Color(0xFFFFF2A1));c.drawCircle(const Offset(6,-6),5,Paint()..color=Colors.white);c.drawCircle(const Offset(8,-6),2.3,Paint()..color=Colors.black);final beak=Path()..moveTo(12,0)..lineTo(24,4)..lineTo(12,8)..close();c.drawPath(beak,Paint()..color=const Color(0xFFFF783E));c.restore();}@override bool shouldRepaint(covariant FlappyPainter old)=>true;}

// MEMORY MATCH — 8 pairs, local best score is fewest moves.
class MemoryGame extends StatefulWidget{const MemoryGame({super.key});@override State<MemoryGame> createState()=>_MemoryGameState();}
class _MemoryGameState extends State<MemoryGame>{final symbols=['🍒','🍋','🍇','🍉','⭐','💎','🍀','🔥'];late List<String>cards;final Set<int>matched={};int? first;int moves=0,seconds=0,best=0;bool locked=false;Timer? clock;
 @override void initState(){super.initState();_newGame();_load();}Future<void>_load()async{final p=await SharedPreferences.getInstance();if(mounted)setState(()=>best=p.getInt('best_memory')??0);}
 void _newGame(){clock?.cancel();clock=null;cards=[...symbols,...symbols]..shuffle();matched.clear();first=null;moves=0;seconds=0;locked=false;if(mounted)setState((){});}
 void _startClock(){clock??=Timer.periodic(const Duration(seconds:1),(_){if(mounted)setState(()=>seconds++);});}
 void _flip(int i){if(locked||matched.contains(i)||i==first)return;_startClock();setState((){if(first==null){first=i;}else{final old=first!;moves++;if(cards[old]==cards[i]){matched.add(old);matched.add(i);first=null;if(matched.length==cards.length){clock?.cancel();clock=null;_save();}}else{locked=true;first=i;Future.delayed(const Duration(milliseconds:650),(){if(!mounted)return;setState((){first=null;locked=false;});});}}});}
 Future<void>_save()async{final p=await SharedPreferences.getInstance();final old=p.getInt('best_memory')??0;if(old==0||moves<old){best=moves;await p.setInt('best_memory',moves);if(mounted)setState((){});}}
 @override void dispose(){clock?.cancel();super.dispose();}
 @override Widget build(BuildContext context){final done=matched.length==cards.length;return Scaffold(appBar:AppBar(title:const Text('🧠 MEMORY MATCH'),actions:[IconButton(onPressed:_newGame,icon:const Icon(Icons.refresh))]),body:SafeArea(child:Column(children:[Padding(padding:const EdgeInsets.all(12),child:Row(mainAxisAlignment:MainAxisAlignment.spaceAround,children:[ScoreBox(label:'MOVES',value:'$moves',color:purple),ScoreBox(label:'TIME',value:'${seconds}s',color:cyan),ScoreBox(label:'BEST',value:best==0?'—':'$best',color:green)])),Expanded(child:Padding(padding:const EdgeInsets.all(12),child:GridView.builder(itemCount:cards.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:4,crossAxisSpacing:9,mainAxisSpacing:9),itemBuilder:(context,i){final show=matched.contains(i)||first==i;return GestureDetector(onTap:()=>_flip(i),child:AnimatedContainer(duration:const Duration(milliseconds:180),decoration:BoxDecoration(color:show?const Color(0xFF29234A):panel,borderRadius:BorderRadius.circular(15),border:Border.all(color:show?purple:Colors.white12,width:show?2:1)),child:Center(child:Text(show?cards[i]:'?',style:TextStyle(fontSize:show?29:28,fontWeight:FontWeight.w900,color:show?Colors.white:purple)))));})),if(done)Padding(padding:const EdgeInsets.only(bottom:18),child:Column(children:[const Text('ALL PAIRS FOUND! 🎉',style:TextStyle(color:green,fontWeight:FontWeight.w900,fontSize:18)),Text('$moves moves • ${seconds}s'),const SizedBox(height:8),FilledButton(onPressed:_newGame,child:const Text('PLAY AGAIN'))]))else const Padding(padding:EdgeInsets.only(bottom:18),child:Text('FLIP CARDS • FIND THE PAIRS',style:TextStyle(color:Colors.white60,fontWeight:FontWeight.w800,letterSpacing:1.3)))])));}
}

// TIC-TAC-TOE difficulty selection.
class DifficultyPage extends StatelessWidget{const DifficultyPage({super.key});@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('❌ TIC-TAC-TOE')),body:Padding(padding:const EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const SizedBox(height:25),const Text('CHOOSE DIFFICULTY',textAlign:TextAlign.center,style:TextStyle(fontSize:23,fontWeight:FontWeight.w900,letterSpacing:1.2)),const SizedBox(height:8),const Text('How tough should the CPU be?',textAlign:TextAlign.center,style:TextStyle(color:Colors.white60)),const SizedBox(height:28),_DifficultyTile(title:'NOOB',desc:'Easy • random moves',icon:'🟢',color:green,onTap:()=>_go(context,0)),_DifficultyTile(title:'MID',desc:'Blocks you and takes winning moves',icon:'🟡',color:const Color(0xFFFFC857),onTap:()=>_go(context,1)),_DifficultyTile(title:'PRO',desc:'Optimal strategy • try not to lose',icon:'🔴',color:const Color(0xFFFF647C),onTap:()=>_go(context,2))]))));}
 void _go(BuildContext context,int level)=>Navigator.push(context,MaterialPageRoute(builder:(_)=>TicTacToe(level:level)));
}
class _DifficultyTile extends StatelessWidget{final String title,desc,icon;final Color color;final VoidCallback onTap;const _DifficultyTile({required this.title,required this.desc,required this.icon,required this.color,required this.onTap});@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.only(bottom:14),child:Material(color:panel,borderRadius:BorderRadius.circular(20),child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(20),child:Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(borderRadius:BorderRadius.circular(20),border:Border.all(color:color.withValues(alpha:.35))),child:Row(children:[Text(icon,style:const TextStyle(fontSize:30)),const SizedBox(width:15),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:TextStyle(color:color,fontSize:17,fontWeight:FontWeight.w900,letterSpacing:1.5)),const SizedBox(height:4),Text(desc,style:const TextStyle(color:Colors.white70,fontSize:12))])),const Icon(Icons.chevron_right)])))));}
class TicTacToe extends StatefulWidget{final int level;const TicTacToe({super.key,required this.level});@override State<TicTacToe> createState()=>_TicTacToeState();}
class _TicTacToeState extends State<TicTacToe>{List<String>board=List.filled(9,'');String status='YOUR TURN';int xWins=0,oWins=0,draws=0;bool busy=false;final rng=Random();
 @override void initState(){super.initState();_load();}Future<void>_load()async{final p=await SharedPreferences.getInstance();if(mounted)setState((){xWins=p.getInt('ttt_x_wins')??0;oWins=p.getInt('ttt_o_wins')??0;draws=p.getInt('ttt_draws')??0;});}
 void _reset()=>setState((){board=List.filled(9,'');status='YOUR TURN';busy=false;});
 void _play(int i){if(busy||board[i].isNotEmpty||status!='YOUR TURN')return;setState(()=>board[i]='X');if(_winner('X')){_finish('YOU WIN!');return;}if(!board.contains('')){_finish('DRAW');return;}setState((){busy=true;status='CPU THINKING...';});Future.delayed(const Duration(milliseconds:250),_cpu);}
 void _cpu(){if(!mounted||status!='CPU THINKING...')return;final i=_chooseMove();setState((){board[i]='O';busy=false;});if(_winner('O')){_finish('CPU WINS');return;}if(!board.contains('')){_finish('DRAW');return;}setState(()=>status='YOUR TURN');}
 int _chooseMove(){final empty=[for(int i=0;i<9;i++)if(board[i].isEmpty)i];if(widget.level==0)return empty[rng.nextInt(empty.length)];if(widget.level==1){for(final i in empty){board[i]='O';final win=_winner('O');board[i]='';if(win)return i;}for(final i in empty){board[i]='X';final win=_winner('X');board[i]='';if(win)return i;}return empty[rng.nextInt(empty.length)];}int bestScore=-999,bestMove=empty.first;for(final i in empty){board[i]='O';final s=_minimax(false,0);board[i]='';if(s>bestScore){bestScore=s;bestMove=i;}}return bestMove;}
 int _minimax(bool maxing,int depth){if(_winner('O'))return 10-depth;if(_winner('X'))return depth-10;if(!board.contains(''))return 0;if(maxing){int b=-999;for(int i=0;i<9;i++){if(board[i].isEmpty){board[i]='O';b=max(b,_minimax(false,depth+1));board[i]='';}}return b;}int b=999;for(int i=0;i<9;i++){if(board[i].isEmpty){board[i]='X';b=min(b,_minimax(true,depth+1));board[i]='';}}return b;}
 bool _winner(String p){const lines=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];return lines.any((l)=>l.every((i)=>board[i]==p));}
 Future<void>_finish(String result)async{setState((){status=result;busy=true;});final p=await SharedPreferences.getInstance();if(result=='YOU WIN!'){xWins++;await p.setInt('ttt_x_wins',xWins);final old=p.getInt('score_ttt')??0;if(xWins>old)await p.setInt('score_ttt',xWins);}else if(result=='CPU WINS'){oWins++;await p.setInt('ttt_o_wins',oWins);}else{draws++;await p.setInt('ttt_draws',draws);}if(mounted)setState((){});}
 String get levelName=>['NOOB','MID','PRO'][widget.level];
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text('TIC-TAC-TOE • $levelName'),actions:[IconButton(onPressed:_reset,icon:const Icon(Icons.refresh))]),body:SafeArea(child:Padding(padding:const EdgeInsets.all(20),child:Column(children:[Row(mainAxisAlignment:MainAxisAlignment.spaceAround,children:[ScoreBox(label:'YOU',value:'$xWins',color:cyan),ScoreBox(label:'DRAWS',value:'$draws',color:purple),ScoreBox(label:'CPU',value:'$oWins',color:const Color(0xFFFF647C))]),const Spacer(),Text(status,style:TextStyle(color:status=='YOU WIN!'?green:status=='CPU WINS'?const Color(0xFFFF647C):Colors.white70,fontWeight:FontWeight.w900,letterSpacing:1.5)),const SizedBox(height:16),AspectRatio(aspectRatio:1,child:GridView.builder(physics:const NeverScrollableScrollPhysics(),itemCount:9,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:3,crossAxisSpacing:9,mainAxisSpacing:9),itemBuilder:(context,i){final v=board[i];return InkWell(onTap:()=>_play(i),borderRadius:BorderRadius.circular(18),child:Ink(decoration:BoxDecoration(color:panel,borderRadius:BorderRadius.circular(18),border:Border.all(color:v=='X'?cyan.withValues(alpha:.4):v=='O'?const Color(0xFFFF647C).withValues(alpha:.4):Colors.white10)),child:Center(child:Text(v,style:TextStyle(fontSize:54,fontWeight:FontWeight.w900,color:v=='X'?cyan:const Color(0xFFFF647C))))));})),const Spacer(),if(status!='YOUR TURN'&&status!='CPU THINKING...')FilledButton(onPressed:_reset,child:const Text('PLAY AGAIN')),const SizedBox(height:10)]))));}
